FROM cassandra:3.10

ADD resources /resources/

# RUN SOURCE '/resources/cassandra.cql'

# RUN cqlsh -f /resources/cassandra.cql
# -u 'my_username' -p 'my_password'

# RUN cqlsh -e "COPY sunbird.page_management(id, appmap,createdby,createddate, name, organisationid, portalmap, updatedby, updateddate) FROM '/resources/pageMgmt.csv'"

# RUN cqlsh -e "COPY sunbird.page_section(id, alt, createdby,createddate, description, display, imgurl, name, searchquery, sectiondatatype,status, updatedby, updateddate) FROM '/resources/pageSection.csv'"

