FROM jboss/keycloak
USER root
# RUN yum install -y git
# git clone https://github.com/juniorojha/scratchpad
# git config --global user.name "Gaurav Ojha"
# git config --global user.email "ojha.iiitm@gmail.com"

